---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z7fun169/public_html
    - /bin/cp -f index.html $DEPLOYPATH/index.html
    - /bin/cp -f admin.html $DEPLOYPATH/admin.html
    - /bin/cp -f .htaccess $DEPLOYPATH/.htaccess
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp -Rf assets/. $DEPLOYPATH/assets/
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -f api/content.php $DEPLOYPATH/api/content.php
    - /bin/cp -f api/upload.php $DEPLOYPATH/api/upload.php
    - /bin/cp -f api/deploy.php $DEPLOYPATH/api/deploy.php
